version: "3"

services:
  server:
    container_name: z35_pserver_zad2
    build:
      context: .
      dockerfile: Dockerfile1
    tty: true
    network_mode: "host"

  client:
    container_name: z35_cclient_zad2
    build:
      context: .
      dockerfile: Dockerfile2
    tty: true
    network_mode: "host"
    depends_on:
      - server
